---
functional:
  - требование 1
  - требование 2
non-functional:
  - требование 3 Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - требование 4 Сайт должен быть безопасным и защищать данные пользователя
  - требование 5 Сайт должен быть удобным на мобильном устройстве
  - требование 6 Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - требование 7 Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 7 сайт должен быть кроссбраузерным
  - требование 8
